server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Custom handling for Unity WebGL Brotli-compressed build framework
    location = /Build/Build.framework.js {
        root /usr/share/nginx/html;
        types { }
        default_type application/javascript;
        add_header Content-Encoding br;
        try_files /Build/Build.framework.js.br =404;
    }

    # Custom handling for Unity WebGL Brotli-compressed build data
    location = /Build/Build.data {
        root /usr/share/nginx/html;
        types { }
        default_type application/octet-stream;
        add_header Content-Encoding br;
        try_files /Build/Build.data.br =404;
    }

    # Custom handling for Unity WebGL Brotli-compressed build WASM
    location = /Build/Build.wasm {
        root /usr/share/nginx/html;
        types { }
        default_type application/wasm;
        add_header Content-Encoding br;
        try_files /Build/Build.wasm.br =404;
    }

    # Custom handling for standard errors
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
